imageStreams:
  - name: penfold-bot
    spec:
      lookupPolicy:
        local: false
buildConfigs:
  - name : penfold-bot
    output:
      to:
        kind: ImageStreamTag
        name: penfold-bot:latest
    source:
      git:
        uri: https://github.com/gorkem/penfold.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: NPM_MIRROR
        from:
          kind: ImageStreamTag
          name: nodejs:6
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: TtpYsucltvyHlUin8ACspxyyIfdML0yimxCey0Tf
      type: GitHub
    - generic:
        secret: pfYWfSAh2A7Duom4Xo03uRidUxVVuiUGKjGCUUFP
      type: Generic
controller: deploymentconfig
name: penfold-bot
replicas: 1
strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
containers:
- env:
  - name: DATABASE_SERVICE_NAME
    value: mongodb
  - name: MONGODB_USER
    valueFrom:
      secretKeyRef:
        key: database-user
        name: penfold-bot
  - name: MONGODB_PASSWORD
    valueFrom:
      secretKeyRef:
        key: database-password
        name: penfold-bot
  - name: MONGODB_DATABASE
    value: penfolddb
  - name: MONGODB_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        key: database-admin-password
        name: penfold-bot
  - name: MATTERMOST_HOST
    value: chat.openshift.io
  - name: MATTERMOST_GROUP
    value: developers
  - name: MATTERMOST_USER
    value: penfold
  - name: MATTERMOST_PASSWORD
    valueFrom:
      secretKeyRef:
        key: mattermost-password
        name: penfold-bot
  - name: EXPRESS_PORT
    value: "8080"
  - name: HUBOT_LOG_LEVEL
    value: debug
  - name: MONGODB_HOST
    value: mongodb
  image: 172.30.208.107:5000/penfold/penfold-bot:latest
  imagePullPolicy: IfNotPresent
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    tcpSocket:
      port: 8080
    timeoutSeconds: 3
  name: nodejs-mongo-persistent
  ports:
  - containerPort: 8080
    protocol: TCP
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 3
    periodSeconds: 10
    successThreshold: 1
    tcpSocket:
      port: 8080
    timeoutSeconds: 3
  resources:
    limits:
      memory: 512Mi
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File
dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler
securityContext: {}
terminationGracePeriodSeconds: 30
triggers:
- imageChangeParams:
    automatic: true
    containerNames:
    - nodejs-mongo-persistent
    from:
      kind: ImageStreamTag
      name: penfold-bot:latest
      namespace: penfold
  type: ImageChange
- type: ConfigChange
